### ISSUE TITLE
[IOS] How can I rename app on Organizer

### ISSUE THREAD

**Issue by izitechworld** [KingWu/flutter_starter_kit#10]
Hi bro,

Thank you for your starter kit! It's really nice for us.

![image](https://user-images.githubusercontent.com/5549954/60332612-30a7dc80-99d2-11e9-8566-ad6a80b16ef9.png)
I'm trying to archive my app to apple but, its showing development...its show be named English Listening...I changed it already.
![image](https://user-images.githubusercontent.com/5549954/60332692-57661300-99d2-11e9-97cd-ba73fb70240a.png)

Please help me if you know that.
Thank you!

**Comment by KingWu** [comment]
Go to Targets in Xcode
Get Info on your project's target (your current development name)
Search for Product Name under Packaging. Change the value of what you want the your new project name to be.

<img width="875" alt="Screen Shot 2019-06-29 at 11 07 18 AM" src="https://user-images.githubusercontent.com/2141985/60379028-19aecc00-9a5e-11e9-8a8b-d25b5ca4832a.png">

**Comment by KingWu** [comment]
@izitechworld solved?
