### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Dreamersoul** [KingWu/flutter_starter_kit#12]
I'm starting to use flutter and I wanted to use this starter kit as a starting point for a project wouldn't it be nice to have a wiki where we can show how to add models, auth, caching and Api routes.

Maybe how to add a screen

Forgive me if that's not the case it's just the files were overwhelming and I wanted to customize it a bit

**Comment by KingWu** [comment]
@Dreamersoul Sorry. it is hard to present knowledges in a tutorial. I just write an article to share my learning path. Hope it can help you. Better to capture knowledages before customizing the flutter_starter_kit as you may face mistake on writing codes.

https://medium.com/@kingwu/flutter-learning-path-d6b3b0235799

**Comment by Dreamersoul** [comment]
Thanks for the response! Will read your post!
