### ISSUE TITLE
[ How to Fix ] type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by philipscheer** [KingWu/flutter_starter_kit#13]
Hi,

I needed to change the RSS from Apple Store:
  static const String _baseUrl = 'https://rss.itunes.apple.com/api/v1'; //  https://itunes.apple.com/hk
  static const String _TOP_FREE_APP_API = '/us/ios-apps/top-free/all/%d/explicit.json'; //https://itunes.apple.com/hk/rss/topfreeapplications/limit=10/json
  static const String _TOP_FEATURE_APP_API = '/us/ios-apps/top-grossing/all/%d/explicit.json';
  static const String _APP_DETAIL_API = '/lookup/json';

Now I'm receiving the issue in some mapping:
<img width="1642" alt="Screen Shot 2019-07-29 at 17 04 34" src="https://user-images.githubusercontent.com/30629616/62078563-44d63800-b223-11e9-8e5e-5724c795f64e.png">
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'

I think the issue was here:
.../flutter_starter_kit/lib/app/model/pojo/response/TopAppResponse.dart

Thanks for your support =)

**Comment by KingWu** [comment]
Yes. The issue came from TopAppResponse.dart.

The core issue is that the response's json structure is changed. Need to change the pojo structure to adapt it

**Comment by KingWu** [comment]
Normally, the type/structure is not matched. Then throw this error _InternalLinkedHashMap<String, dynamic>

**Comment by philipscheer** [comment]
Thanks for your return, will change the pojo structure if you allow or want I could make a branch to other to compare.
