### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by iwxfer** [KingWu/flutter_starter_kit#14]
Running "flutter pub get" in flutter_starter_kit...                 2.7s
Launching lib\config\main_development.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Finished with error: Please review your Gradle project setup in the android/ folder.
* Error running Gradle:
ProcessException: Process "C:\dev\flutter_starter_kit\android\gradlew.bat" exited abnormally:
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :app
app: 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'com.github.bumptech.glide:compiler:4.8.0' and apply the kapt plugin: "apply plugin: 'kotlin-kapt'".

> Configure project :path_provider

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':path_provider'.
> Could not resolve all artifacts for configuration ':path_provider:classpath'.
   > Could not download builder.jar (com.android.tools.build:builder:3.3.0)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.0/builder-3.3.0.jar'.
         > Read timed out
   > Could not download manifest-merger.jar (com.android.tools.build:manifest-merger:26.3.0)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/manifest-merger/26.3.0/manifest-merger-26.3.0.jar'.
         > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/manifest-merger/26.3.0/manifest-merger-26.3.0.jar'.
            > Connection reset
   > Could not download bundletool.jar (com.android.tools.build:bundletool:0.6.0)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.6.0/bundletool-0.6.0.jar'.
         > Read timed out
   > Could not download protos.jar (com.android.tools.analytics-library:protos:26.3.0)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/protos/26.3.0/protos-26.3.0.jar'.
         > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 14s
  Command: C:\dev\flutter_starter_kit\android\gradlew.bat app:properties

**Comment by KingWu** [comment]
Seems your location is blocked by Google

https://stackoverflow.com/questions/55492278/flutter-run-failed-a-problem-occurred-configuring-project-shared-preferences
