### ISSUE TITLE
How do I run this app

### ISSUE THREAD

**Issue by brianoh** [KingWu/flutter_starter_kit#16]
Hi, I've run a large number of Flutter apps that I've downloaded from github, but I cannot see how to run this. There is no main.dart, and I don't know how to run config. Can you please advise.

**Comment by KingWu** [comment]
For development,
flutter run --flavor development -t lib/config/main_development.dart

For staging,
flutter run --flavor staging -t lib/config/main_staging.dart

For production,
flutter run --flavor production -t lib/config/main_production.dart
