### ISSUE TITLE
Please solve the infinite loading problem!

### ISSUE THREAD

**Issue by kokochi66** [KingWu/flutter_starter_kit#18]
Hello @KingWu ! I am trying to solve the infinite loading problem in this starter-kit
Many attempts have been made to identify the cause.
And then, I found that after entering 'Entry _$EntryFromJson' of "Entry.g.dart' to be infinitely loading.
![theProblems1](https://user-images.githubusercontent.com/61536109/83713227-81a06600-a662-11ea-9c90-036c40de3b4d.png)
![theProblems2](https://user-images.githubusercontent.com/61536109/83713228-8238fc80-a662-11ea-8bb7-ce7a1a70afff.png)

In the console, the previous code works fine.
After entering '$EntryFromJson', it is confirmed that the operation stops.
To check this, I used a simple method to print messages to the console.

I think, 'void _showLoading' function in 'HomePadge.dart'  is displays the loading screen, and it doesn't seem to go to the next screen.

I don't know how to solve this problem from here on.
Help me Please!!!

**Comment by KingWu** [comment]
@kokochi66 Thanks for tracing the issue. i created a branch `fix-loading-issue ` to fix the issue. found that the issue come from the API change. Will fix it soon

**Comment by KingWu** [comment]
@kokochi66 release 1.4.0 to fix the existing issues. Sorry to make you feel plain. Enjoy your Flutter learning trip
