### ISSUE TITLE
APIProvider

### ISSUE THREAD

**Issue by dyardyGIT** [KingWu/flutter_starter_kit#3]
I am learning from your patten and using the APIProvider class to make calls to an api.  Question if i have new api end point which doesn't use the _baseUrl how would i use _dio 

currently...
static const String _newAPIUrl = 'https://www.test.com/api/'

if i use _dio.post(APIProvider._newAPIUrl, data: data);
the url path is pre-pended with the _baseUrl

How can I avoid in nice way the pre-pending of the _baseUrl value?
thx

**Comment by KingWu** [comment]
If you don't use DioOptions to setup baseURL, 

Just comment
//Options dioOptions = Options()
//      ..baseUrl = Env.value.baseUrl

and let say your api with full path
static const String _API1 = 'https://www.test.com/api/api1'

you need to use full path, 
_dio.post(_API1, data: data)
