### ISSUE TITLE
[flutter run -t homepage.dart] Showing empty

### ISSUE THREAD

**Issue by izitechworld** [KingWu/flutter_starter_kit#4]
Hi KingWu,

I'd like to say hello first. I really love your starter kit.
I'm a newbie of flutter. Could you help me how to run your example?
![image](https://user-images.githubusercontent.com/5549954/52696825-960aac00-2fa2-11e9-8619-9cda01f5c842.png)
its empty now!
I'm using this command:  flutter run -t lib/app/ui/page/HomePage.dart
and  also flutter run -t lib/app/ui/page/AppDetailPage.dart 
They are the same result.
Please give me a help.
Email: vult.pnv@gmail.com
Skype: vult.pnv

Regards and waiting for ur help!

**Comment by KingWu** [comment]
For this starter kit, there exist three flavors including 'development', 'staging' and 'production'

For development,
flutter run --flavor development -t lib/config/main_development.dart

For staging,
flutter run --flavor staging -t lib/config/main_staging.dart

For production,
flutter run --flavor production -t lib/config/main_production.dart

Hope these can help you.

**Comment by izitechworld** [comment]
I solved it

**Comment by izitechworld** [comment]
Thank you.
You are very kind!

--
Thank you for taking the time to read this.
Sincerely,
------------------------------
*Johnny*
*Thanh Vu. Le (Mr.) *
*ILives | Innovation Lives | **http://ilives.us/ <http://ilives.us/>*
Job: Mobile Developer
Tell: (84)
(
91)7
26-2
438
Mail:  *vult.pnv@gmail.com* <vult.pnv@gmail.com>
Skype: *vult.pnv*
