### ISSUE TITLE
too old

### ISSUE THREAD

**Issue by DavidMGT** [KingWu/flutter_starter_kit#7]
The current Dart SDK version is 2.3.0-dev.0.0.flutter-8e73b3c006.

Because dashboard depends on flutter_staggered_grid_view >=0.1.1 <0.2.2 which requires SDK version >=1.19.0 <2.0.0, version solving failed.

pub get failed (1)

**Comment by KingWu** [comment]
Understand your issue. But,  the issue ia out of this example 's scope as it does not demonstrate to use flutter staggered grid view.

**Comment by KingWu** [comment]
Understand your issue. But,  the issue ia out of this example 's scope as it does not demonstrate to use flutter staggered grid view.
