### ISSUE TITLE
Help In Visual Studio Code

### ISSUE THREAD

**Issue by ashishnimrot** [KingWu/flutter_starter_kit#9]
flutter_starter_kit ashish$ flutter run lib/utility/framework/Application.dart
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/utility/framework/Application.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                             10.2s
Resolving dependencies...
  177.4s (!)

The Gradle project does not define a task suitable for the requested build.
The android/app/build.gradle file defines product flavors: development, production, staging
You must specify a --flavor option to select one of them.
Gradle build aborted.

**Comment by KingWu** [comment]
Take a took on this issue. You run with a wrong Dart file

https://github.com/KingWu/flutter_starter_kit/issues/4#issuecomment-463117894

**Comment by KingWu** [comment]
Will close it if no issue found
